import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./loginBtn";
import LogoutBtn from "./logoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions); // 서버 컴포넌트, 서버 기능 안에서 사용

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="header">
          <Link href="/" className="main-logo">
            <h1>
              MIDOO
              {/* <span className="sub-tit">디지털 리터러시의 혁신</span> */}
            </h1>
          </Link>
          <>
            {session ? (
              <div className="user-name">
                안녕하세요{" "}
                <span className="user-strong">{session.user.name}</span>님 좋은
                하루에요!
                <LogoutBtn></LogoutBtn>
              </div>
            ) : (
              <p>
                안녕하세요 좋은 하루입니다! 로그인하세요!
                <LoginBtn></LoginBtn>
              </p>
            )}
          </>
        </div>

        {children}

        <div className="footer">
          <Link href="/" className="bottom-gnb">
            홈
          </Link>
          <Link href="/list" className="bottom-gnb">
            리스트
          </Link>
          <Link href="/write" className="bottom-gnb">
            글쓰기
          </Link>
          <Link href="/mypage" className="bottom-gnb">
            마이페이지
          </Link>
        </div>
      </body>
    </html>
  );
}
