import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./loginBtn";
import LogoutBtn from "./logoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions); // 서버 컴포넌트, 서버 기능 안에서 사용

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="inner">
          <div className="header">
            <div className="link-wrap">
              <Link href="/" className="bottom-gnb">
                Home
              </Link>
              <Link href="/list" className="bottom-gnb">
                article
              </Link>
              <Link href="/write" className="bottom-gnb">
                write
              </Link>
              <Link href="/mypage" className="bottom-gnb">
                mypage
              </Link>
            </div>
            <div className="right-login">
              {session ? (
                <div className="user-name">
                  안녕하세요{" "}
                  <span className="user-strong">{session.user.name}</span>님
                  좋은 하루에요!
                  <LogoutBtn></LogoutBtn>
                </div>
              ) : (
                <p>
                  안녕하세요 좋은 하루입니다! 로그인하세요!
                  <LoginBtn></LoginBtn>
                </p>
              )}
            </div>
          </div>

          {children}

          <div className="footer"></div>
        </div>
      </body>
    </html>
  );
}
